# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: install dependencies
        run: sudo apt update && sudo apt install libblosc1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2.3.4
      - name: publish package
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u publisher --password-stdin docker.pkg.github.com
          docker build -t docker.pkg.github.com/keeneyetech/bioformats2raw/bioformats2raw .
          docker push docker.pkg.github.com/keeneyetech/bioformats2raw/bioformats2raw
